name: Trigger blog build

on:
  push:
    branches:
      - main

jobs:
  build-blog:
    runs-on: ubuntu-latest
    steps:
      - name: Create repository dispatch event
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh api repos/ORG/REPO/dispatches --raw-field event_type=update-theme
